import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Iniciando seed do banco de dados...\n');

  const hashedPassword = await bcrypt.hash('senha123', 10);
  
  const user = await prisma.user.upsert({
    where: { email: 'usuario@exemplo.com' },
    update: {},
    create: {
      name: 'Usuário Exemplo',
      email: 'usuario@exemplo.com',
      password: hashedPassword,
    },
  });

  console.log('✅ Usuário criado:', user.email);

  const movies = [
    {
      title: 'Bumblebee',
      originalTitle: 'Bumblebee',
      releaseDate: new Date('2018-12-21'),
      description: 'Na Califórnia de 1987, Bumblebee encontra refúgio em um ferro-velho de uma pequena cidade. Charlie, uma jovem de 18 anos, o descobre e rapidamente percebe que este não é um Fusca amarelo comum.',
      duration: 114,
      budget: 135000000,
      revenue: 467989762,
      posterUrl: 'https://image.tmdb.org/t/p/w500/fw02ONlDhrYjTSZV8XO6hhU3ds3.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/hMANgfPHR1tRObNp2oPiOi9mMlz.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=lcwmDAYt22k',
      genre: 'Ação, Aventura, Ficção Científica',
      director: 'Travis Knight',
      cast: 'Hailee Steinfeld, John Cena, Jorge Lendeborg Jr.',
      rating: 6.7,
      status: 'Lançado',
      voteCount: 5703,
      voteAverage: 6.7,
      userId: user.id,
    },
    {
      title: 'Capitã Marvel',
      originalTitle: 'Captain Marvel',
      releaseDate: new Date('2019-03-08'),
      description: 'Carol Danvers se torna uma das heroínas mais poderosas do universo quando a Terra fica no meio de uma guerra galáctica entre duas raças alienígenas.',
      duration: 124,
      budget: 152000000,
      revenue: 1128274794,
      posterUrl: 'https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=Z1BCujX3pw8',
      genre: 'Ação, Aventura, Ficção Científica',
      director: 'Anna Boden, Ryan Fleck',
      cast: 'Brie Larson, Samuel L. Jackson, Ben Mendelsohn',
      rating: 6.9,
      status: 'Lançado',
      voteCount: 12500,
      voteAverage: 6.9,
      userId: user.id,
    },
    {
      title: 'Alita: Anjo de Combate',
      originalTitle: 'Alita: Battle Angel',
      releaseDate: new Date('2019-02-14'),
      description: 'Alita é uma ciborgue que desperta em um futuro pós-apocalíptico sem memória de quem é. Ela embarca em uma jornada para descobrir seu passado.',
      duration: 122,
      budget: 170000000,
      revenue: 404852543,
      posterUrl: 'https://image.tmdb.org/t/p/w500/xRWht48C2V8XNfzvPehyClOvDni.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/8RKBHHRqOMOLh5qW3sS6TSFTd8h.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=w7pYhpJaJW8',
      genre: 'Ação, Ficção Científica, Aventura',
      director: 'Robert Rodriguez',
      cast: 'Rosa Salazar, Christoph Waltz, Jennifer Connelly',
      rating: 7.2,
      status: 'Lançado',
      voteCount: 8900,
      voteAverage: 7.2,
      userId: user.id,
    },
    {
      title: 'Como Treinar o Seu Dragão 3',
      originalTitle: 'How to Train Your Dragon: The Hidden World',
      releaseDate: new Date('2019-02-22'),
      description: 'Soluço e Banguela descobrem uma caverna de gelo que abriga centenas de novos dragões selvagens e um misterioso Fúria da Noite.',
      duration: 104,
      budget: 129000000,
      revenue: 525700000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/h3KN24PrOheHVYs9ypuOIdFBEpX.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=2BP38770KNo',
      genre: 'Animação, Família, Aventura',
      director: 'Dean DeBlois',
      cast: 'Jay Baruchel, America Ferrera, F. Murray Abraham',
      rating: 7.5,
      status: 'Lançado',
      voteCount: 7200,
      voteAverage: 7.5,
      userId: user.id,
    },
    {
      title: 'Aquaman',
      originalTitle: 'Aquaman',
      releaseDate: new Date('2018-12-21'),
      description: 'Arthur Curry, o herdeiro do reino submarino de Atlântida, precisa assumir seu destino como Aquaman e liderar seu povo contra seu meio-irmão Orm.',
      duration: 143,
      budget: 160000000,
      revenue: 1148461807,
      posterUrl: 'https://image.tmdb.org/t/p/w500/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/7icgF1dgUJaCpnWV235eafXFznJ.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=WDkg3h8PCVU',
      genre: 'Ação, Aventura, Fantasia',
      director: 'James Wan',
      cast: 'Jason Momoa, Amber Heard, Willem Dafoe',
      rating: 6.9,
      status: 'Lançado',
      voteCount: 14200,
      voteAverage: 6.9,
      userId: user.id,
    },
    {
      title: 'Nossa Culpa',
      originalTitle: 'Your Fault',
      releaseDate: new Date('2024-12-27'),
      description: 'A sequência de Minha Culpa continua a história de amor turbulenta entre Noah e Nick.',
      duration: 118,
      budget: 5000000,
      revenue: 15000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/tPq8xqhsTYZzUGwMKuksa0eyeGZ.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/3EIYw0nOkD2ITnKZAqNSJ5HxHJJ.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=example1',
      genre: 'Romance, Drama',
      director: 'Domingo González',
      cast: 'Nicole Wallace, Gabriel Guevara',
      rating: 7.8,
      status: 'Lançado',
      voteCount: 2500,
      voteAverage: 7.8,
      userId: user.id,
    },
    {
      title: 'Furioza 2',
      originalTitle: 'Furioza 2',
      releaseDate: new Date('2024-10-11'),
      description: 'Anos após um assassinato, o novo líder da Furioza, Golden, toma as rédeas de um sindicato vigilante e assume um novo foco entre as fronteiras.',
      duration: 110,
      budget: 8000000,
      revenue: 12000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/huvM6PcelNHpL3ldtgDpxstQWqN.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=example2',
      genre: 'Ação, Crime, Thriller',
      director: 'Cyprian T. Olencki',
      cast: 'Weronika Książkiewicz, Mateusz Banasiuk',
      rating: 6.5,
      status: 'Lançado',
      voteCount: 1800,
      voteAverage: 6.5,
      userId: user.id,
    },
    {
      title: 'Captain Hook - The Cursed Tides',
      originalTitle: 'Captain Hook - The Cursed Tides',
      releaseDate: new Date('2024-09-15'),
      description: 'Uma aventura sombria seguindo o Capitão Gancho em sua busca por vingança contra Peter Pan.',
      duration: 95,
      budget: 3000000,
      revenue: 5000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/7SHFZKfd270y47sXN2WsURUO3ml.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/example3.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=example3',
      genre: 'Aventura, Ação, Terror',
      director: 'John Smith',
      cast: 'Tom Hardy, Emma Watson',
      rating: 5.0,
      status: 'Lançado',
      voteCount: 900,
      voteAverage: 5.0,
      userId: user.id,
    },
    {
      title: 'A Guerra dos Mundos',
      originalTitle: 'War of the Worlds',
      releaseDate: new Date('2024-08-20'),
      description: 'Uma invasão alienígena ameaça a humanidade nesta adaptação moderna do clássico de H.G. Wells.',
      duration: 102,
      budget: 15000000,
      revenue: 25000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/yvirUYrva23IudARHn3mMGVxWqM.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/example4.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=example4',
      genre: 'Ficção científica, Thriller',
      director: 'Steven Spielberg',
      cast: 'Tom Cruise, Dakota Fanning',
      rating: 4.4,
      status: 'Lançado',
      voteCount: 3200,
      voteAverage: 4.4,
      userId: user.id,
    },
    {
      title: 'Invocação do Mal - O Último Ritual',
      originalTitle: 'The Conjuring: Last Rites',
      releaseDate: new Date('2024-09-06'),
      description: 'Ed e Lorraine Warren enfrentam seu caso mais aterrorizante em uma última batalha contra forças demoníacas.',
      duration: 112,
      budget: 39000000,
      revenue: 180000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/40nHGUfypLhlr7gJx8At1IbYkaK.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/example5.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=example5',
      genre: 'Terror',
      director: 'Michael Chaves',
      cast: 'Patrick Wilson, Vera Farmiga',
      rating: 6.9,
      status: 'Lançado',
      voteCount: 5600,
      voteAverage: 6.9,
      userId: user.id,
    },
    {
      title: 'Bacurau',
      originalTitle: 'Bacurau',
      releaseDate: new Date('2019-08-29'),
      description:
        'Uma pequena comunidade no sertão brasileiro descobre que está sendo caçada por estrangeiros.',
      duration: 132,
      budget: 2800000,
      revenue: 3500000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/h3fwlU2jH8aXxwDFmO7D4n8HHaP.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/nQfd8IMyWlZnPQp3LgG2IXA5zHS.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=qlheAOcF-5Y',
      genre: 'Drama, Ficção Científica, Faroeste',
      director: 'Kleber Mendonça Filho, Juliano Dornelles',
      cast: 'Sônia Braga, Udo Kier, Bárbara Colen',
      rating: 7.8,
      status: 'Lançado',
      voteCount: 4000,
      voteAverage: 7.8,
      userId: user.id,
    },
    {
      title: 'Carandiru',
      originalTitle: 'Carandiru',
      releaseDate: new Date('2003-04-11'),
      description:
        'A rotina e as histórias de prisioneiros na Casa de Detenção de São Paulo antes do massacre de 1992.',
      duration: 145,
      budget: 5000000,
      revenue: 12000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/wHYttC8Wx5DhrVmdR4AXxd9UOGx.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/fqPrnQL0M4vdKYpssTLvZxTqkuf.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=6gFqN5nDTMg',
      genre: 'Drama, Crime',
      director: 'Hector Babenco',
      cast: 'Luiz Carlos Vasconcelos, Rodrigo Santoro, Wagner Moura',
      rating: 7.4,
      status: 'Lançado',
      voteCount: 2100,
      voteAverage: 7.4,
      userId: user.id,
    },
    {
      title: 'Que Horas Ela Volta?',
      originalTitle: 'Que Horas Ela Volta?',
      releaseDate: new Date('2015-08-27'),
      description:
        'A vida de uma empregada doméstica muda quando sua filha vem morar na casa dos patrões.',
      duration: 112,
      budget: 2500000,
      revenue: 4400000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/p0z3UXr9cwPzE1KpFmPtqNRVzDL.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/3mLGMyYXogXXz4qBvyovOZlCYy2.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=svI0h2qtEfM',
      genre: 'Drama',
      director: 'Anna Muylaert',
      cast: 'Regina Casé, Camila Márdila, Michel Joelsas',
      rating: 8.0,
      status: 'Lançado',
      voteCount: 1500,
      voteAverage: 8.0,
      userId: user.id,
    },
    {
      title: 'O Homem que Copiava',
      originalTitle: 'O Homem que Copiava',
      releaseDate: new Date('2003-08-15'),
      description:
        'Um operador de fotocopiadora em Porto Alegre se envolve em crimes para conquistar a mulher que ama.',
      duration: 123,
      budget: 1500000,
      revenue: 2500000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/oz7M6BFrgX8aL7Kc9xF7nMPLb7K.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/oq3YcoD91uh3CZnDFpIDuIG29cH.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=AmBPZSpSLfQ',
      genre: 'Comédia, Crime, Romance',
      director: 'Jorge Furtado',
      cast: 'Lázaro Ramos, Leandra Leal, Pedro Cardoso',
      rating: 7.7,
      status: 'Lançado',
      voteCount: 1200,
      voteAverage: 7.7,
      userId: user.id,
    },
    {
      title: 'Meu Nome Não É Johnny',
      originalTitle: 'Meu Nome Não É Johnny',
      releaseDate: new Date('2008-01-04'),
      description:
        'João Estrella é um jovem da elite carioca que se torna o maior traficante da zona sul do Rio.',
      duration: 122,
      budget: 3000000,
      revenue: 11000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/wZVvLeIFxLz7KMPL4mYcHwtmsTG.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/vXj2ENo6vKZo1tuy0FsILwLjRLX.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=Q0YhUlYj5Uw',
      genre: 'Drama, Biografia, Crime',
      director: 'Mauro Lima',
      cast: 'Selton Mello, Cléo Pires, Júlia Lemmertz',
      rating: 7.3,
      status: 'Lançado',
      voteCount: 1900,
      voteAverage: 7.3,
      userId: user.id,
    },
    {
      title: 'Hoje Eu Quero Voltar Sozinho',
      originalTitle: 'Hoje Eu Quero Voltar Sozinho',
      releaseDate: new Date('2014-03-28'),
      description:
        'Leonardo, um adolescente cego, descobre sentimentos novos quando conhece o colega Gabriel.',
      duration: 96,
      budget: 2000000,
      revenue: 3000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/2M3rjT9jgDGRU2k4k2HqB5QpBrI.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/8GHfg7yYtQ3OGn3bTQeIMAB7WhZ.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=KfZ9rVb2c6A',
      genre: 'Drama, Romance',
      director: 'Daniel Ribeiro',
      cast: 'Ghilherme Lobo, Fábio Audi, Tess Amorim',
      rating: 8.1,
      status: 'Lançado',
      voteCount: 1600,
      voteAverage: 8.1,
      userId: user.id,
    },
    {
      title: 'Lisbela e o Prisioneiro',
      originalTitle: 'Lisbela e o Prisioneiro',
      releaseDate: new Date('2003-08-22'),
      description:
        'Um malandro e uma moça sonhadora se apaixonam em meio a um cenário de humor e aventura no Nordeste.',
      duration: 108,
      budget: 1800000,
      revenue: 9000000,
      posterUrl: 'https://image.tmdb.org/t/p/w500/b7LJcc6Ot0bXyL5C1jPSH2mUjZX.jpg',
      backdropUrl: 'https://image.tmdb.org/t/p/original/ew2EnT8XrY8wv7RpOawUguFweZT.jpg',
      trailerUrl: 'https://www.youtube.com/watch?v=E6nZ8XqNqYI',
      genre: 'Comédia, Romance',
      director: 'Guel Arraes',
      cast: 'Selton Mello, Débora Falabella, Bruno Garcia',
      rating: 7.6,
      status: 'Lançado',
      voteCount: 1300,
      voteAverage: 7.6,
      userId: user.id,
    },
  ];

  console.log('\n📽️  Criando filmes...\n');

  for (const movieData of movies) {
    const movie = await prisma.movie.upsert({
      where: { 
        id: `seed-${movieData.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}` 
      },
      update: {},
      create: {
        ...movieData,
        id: `seed-${movieData.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
      },
    });
    console.log(`  ✓ ${movie.title}`);
  }

  console.log('\n✅ Seed concluído com sucesso!\n');
  console.log('📊 Resumo:');
  console.log(`  • Usuários: 1`);
  console.log(`  • Filmes: ${movies.length}\n`);
  console.log('🔑 Credenciais de login:');
  console.log(`  Email: usuario@exemplo.com`);
  console.log(`  Senha: senha123\n`);
}

main()
  .catch((e) => {
    console.error('❌ Erro ao executar seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
